import { Recipe, UserProfile } from './types'

export const MOCK_USER: UserProfile = {
  name: 'Alex Silva',
  avatar: 'https://img.usecurling.com/ppl/medium?gender=male',
  gender: 'male',
  age: 28,
  weight: 78,
  height: 178,
  activityLevel: 'Moderado',
  goal: 'Emagrecer',
  dietaryRestrictions: [],
  calorieGoal: 2200,
  waterGoal: 2500,
}

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Bowl de Frango e Quinoa',
    image: 'https://img.usecurling.com/p/400/300?q=chicken%20quinoa%20bowl',
    calories: 450,
    protein: 35,
    carbs: 45,
    fats: 12,
    prepTime: 25,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Salgadas',
    tags: ['Sem Glúten', 'Proteico'],
    ingredients: [
      { name: 'Peito de Frango', amount: '150g', category: 'Carnes/Proteínas' },
      { name: 'Quinoa Cozida', amount: '100g', category: 'Despensa' },
      { name: 'Abacate', amount: '1/2 unid', category: 'Hortifrúti' },
      { name: 'Tomate Cereja', amount: '50g', category: 'Hortifrúti' },
    ],
    instructions: [
      'Grelhe o frango temperado com sal e limão.',
      'Cozinhe a quinoa conforme instruções da embalagem.',
      'Corte o abacate e os tomates.',
      'Monte o bowl e sirva.',
    ],
    rating: 4.8,
  },
  {
    id: '2',
    title: 'Panqueca de Banana Fit',
    image: 'https://img.usecurling.com/p/400/300?q=banana%20pancakes',
    calories: 320,
    protein: 15,
    carbs: 40,
    fats: 8,
    prepTime: 15,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Lanches',
    tags: ['Sem Glúten', 'Vegetariano'],
    ingredients: [
      { name: 'Banana', amount: '1 unid', category: 'Hortifrúti' },
      { name: 'Ovo', amount: '2 unid', category: 'Carnes/Proteínas' },
      { name: 'Aveia', amount: '2 col. sopa', category: 'Despensa' },
      { name: 'Canela', amount: 'a gosto', category: 'Despensa' },
    ],
    instructions: [
      'Amasse a banana.',
      'Misture com os ovos e a aveia.',
      'Despeje em uma frigideira untada.',
      'Doure os dois lados.',
    ],
    rating: 4.5,
  },
  {
    id: '3',
    title: 'Salmão Grelhado com Aspargos',
    image: 'https://img.usecurling.com/p/400/300?q=salmon%20asparagus',
    calories: 520,
    protein: 42,
    carbs: 10,
    fats: 30,
    prepTime: 30,
    portions: 1,
    difficulty: 'Médio',
    category: 'Salgadas',
    tags: ['Low Carb', 'Sem Glúten', 'Sem Lactose'],
    ingredients: [
      { name: 'Filé de Salmão', amount: '180g', category: 'Carnes/Proteínas' },
      { name: 'Aspargos', amount: '100g', category: 'Hortifrúti' },
      { name: 'Azeite de Oliva', amount: '1 col. chá', category: 'Despensa' },
    ],
    instructions: [
      'Tempere o salmão com sal e pimenta.',
      'Grelhe o salmão por 5-7 minutos de cada lado.',
      'Refogue os aspargos no azeite até ficarem macios.',
    ],
    rating: 4.9,
  },
  {
    id: '4',
    title: 'Smoothie Verde Detox',
    image: 'https://img.usecurling.com/p/400/300?q=green%20smoothie',
    calories: 180,
    protein: 5,
    carbs: 35,
    fats: 2,
    prepTime: 5,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Drinks',
    tags: ['Vegan', 'Sem Lactose'],
    ingredients: [
      { name: 'Espinafre', amount: '1 xícara', category: 'Hortifrúti' },
      { name: 'Maçã Verde', amount: '1 unid', category: 'Hortifrúti' },
      { name: 'Água de Coco', amount: '200ml', category: 'Despensa' },
      { name: 'Gengibre', amount: '1 pedaço', category: 'Hortifrúti' },
    ],
    instructions: ['Bata tudo no liquidificador com gelo até ficar homogêneo.'],
    rating: 4.2,
  },
  {
    id: '5',
    title: 'Omelete de Legumes',
    image: 'https://img.usecurling.com/p/400/300?q=vegetable%20omelette',
    calories: 280,
    protein: 18,
    carbs: 8,
    fats: 20,
    prepTime: 10,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Salgadas',
    tags: ['Vegetariano', 'Low Carb'],
    ingredients: [
      { name: 'Ovos', amount: '3 unid', category: 'Carnes/Proteínas' },
      { name: 'Espinafre', amount: '50g', category: 'Hortifrúti' },
      { name: 'Queijo Branco', amount: '30g', category: 'Laticínios' },
    ],
    instructions: [
      'Bata os ovos.',
      'Misture o espinafre picado e o queijo.',
      'Cozinhe em fogo médio até firmar.',
    ],
    rating: 4.6,
  },
  {
    id: '6',
    title: 'Iogurte com Frutas Vermelhas',
    image: 'https://img.usecurling.com/p/400/300?q=yogurt%20berries',
    calories: 220,
    protein: 12,
    carbs: 30,
    fats: 6,
    prepTime: 5,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Sobremesas',
    tags: ['Vegetariano'],
    ingredients: [
      { name: 'Iogurte Natural', amount: '170g', category: 'Laticínios' },
      { name: 'Frutas Vermelhas', amount: '100g', category: 'Hortifrúti' },
      { name: 'Mel', amount: '1 col. chá', category: 'Despensa' },
    ],
    instructions: [
      'Monte em camadas o iogurte e as frutas.',
      'Finalize com mel.',
    ],
    rating: 4.7,
  },
]
