import { Recipe, UserProfile } from './types'

export const MOCK_USER: UserProfile = {
  name: 'Alex Silva',
  avatar: 'https://img.usecurling.com/ppl/medium?gender=male',
  gender: 'male',
  age: 28,
  weight: 78,
  height: 178,
  activityLevel: 'Moderado',
  goal: 'Emagrecer',
  dietaryRestrictions: [],
  calorieGoal: 2200,
  proteinGoal: 160,
  carbsGoal: 200,
  fatsGoal: 70,
  waterGoal: 2500,
}

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Bowl de Frango e Quinoa',
    image: 'https://img.usecurling.com/p/400/300?q=chicken%20quinoa%20bowl',
    calories: 450,
    protein: 35,
    carbs: 45,
    fats: 12,
    prepTime: 25,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Salgadas',
    tags: ['Sem Glúten', 'Proteico'],
    ingredients: [
      { name: 'Peito de Frango', amount: '150g', category: 'Carnes/Proteínas' },
      { name: 'Quinoa Cozida', amount: '100g', category: 'Despensa' },
      { name: 'Abacate', amount: '1/2 unid', category: 'Hortifrúti' },
      { name: 'Tomate Cereja', amount: '50g', category: 'Hortifrúti' },
    ],
    instructions: [
      'Corte o peito de frango em cubos de 2cm e tempere com sal, pimenta e limão.',
      'Aqueça uma frigideira antiaderente e grelhe o frango por 8-10 minutos até dourar.',
      'Enquanto isso, cozinhe a quinoa em água fervente por 15 minutos e escorra.',
      'Corte o abacate em fatias finas e os tomates cereja ao meio.',
      'Monte o bowl colocando a quinoa na base, o frango ao lado, e finalize com os vegetais.',
    ],
    rating: 4.8,
  },
  {
    id: '2',
    title: 'Panqueca de Banana Fit',
    image: 'https://img.usecurling.com/p/400/300?q=banana%20pancakes',
    calories: 320,
    protein: 15,
    carbs: 40,
    fats: 8,
    prepTime: 15,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Lanches',
    tags: ['Sem Glúten', 'Vegetariano'],
    ingredients: [
      { name: 'Banana Prata', amount: '1 unid', category: 'Hortifrúti' },
      { name: 'Ovos', amount: '2 unid', category: 'Carnes/Proteínas' },
      { name: 'Aveia em Flocos', amount: '2 col. sopa', category: 'Despensa' },
      { name: 'Canela em Pó', amount: '1 col. chá', category: 'Despensa' },
    ],
    instructions: [
      'Em uma tigela, amasse bem a banana com um garfo até virar um purê.',
      'Adicione os dois ovos e bata bem com um garfo ou fouet.',
      'Incorpore a aveia e a canela à mistura até ficar homogêneo.',
      'Aqueça uma frigideira untada com um fio de azeite ou óleo de coco.',
      'Despeje porções da massa e doure por cerca de 2 minutos de cada lado.',
    ],
    rating: 4.5,
  },
  {
    id: '3',
    title: 'Salmão Grelhado com Aspargos',
    image: 'https://img.usecurling.com/p/400/300?q=salmon%20asparagus',
    calories: 520,
    protein: 42,
    carbs: 10,
    fats: 30,
    prepTime: 30,
    portions: 1,
    difficulty: 'Médio',
    category: 'Salgadas',
    tags: ['Low Carb', 'Sem Glúten', 'Sem Lactose'],
    ingredients: [
      { name: 'Filé de Salmão', amount: '180g', category: 'Carnes/Proteínas' },
      { name: 'Aspargos Frescos', amount: '100g', category: 'Hortifrúti' },
      { name: 'Azeite de Oliva', amount: '1 col. sopa', category: 'Despensa' },
      { name: 'Limão Siciliano', amount: '1/2 unid', category: 'Hortifrúti' },
    ],
    instructions: [
      'Tempere o filé de salmão com sal, pimenta do reino e suco de meio limão.',
      'Lave os aspargos e corte a parte fibrosa da base (aprox. 2cm).',
      'Aqueça o azeite em uma frigideira grande em fogo médio-alto.',
      'Grelhe o salmão com a pele para baixo por 5 minutos até ficar crocante.',
      'Vire o salmão e adicione os aspargos na mesma frigideira.',
      'Cozinhe por mais 3-4 minutos até o salmão estar no ponto e aspargos macios.',
    ],
    rating: 4.9,
  },
  {
    id: '4',
    title: 'Smoothie Verde Detox',
    image: 'https://img.usecurling.com/p/400/300?q=green%20smoothie',
    calories: 180,
    protein: 5,
    carbs: 35,
    fats: 2,
    prepTime: 5,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Drinks',
    tags: ['Vegan', 'Sem Lactose'],
    ingredients: [
      { name: 'Espinafre', amount: '1 xícara', category: 'Hortifrúti' },
      { name: 'Maçã Verde', amount: '1 unid', category: 'Hortifrúti' },
      { name: 'Água de Coco', amount: '200ml', category: 'Despensa' },
      { name: 'Gengibre', amount: '2cm', category: 'Hortifrúti' },
      { name: 'Limão', amount: 'Suco de 1/2', category: 'Hortifrúti' },
    ],
    instructions: [
      'Lave bem as folhas de espinafre e corte a maçã em cubos (com casca).',
      'Descasque o pedaço de gengibre.',
      'Coloque todos os ingredientes no liquidificador.',
      'Adicione gelo a gosto e bata na velocidade máxima por 1 minuto.',
      'Sirva imediatamente sem coar para aproveitar as fibras.',
    ],
    rating: 4.2,
  },
  {
    id: '5',
    title: 'Omelete de Legumes',
    image: 'https://img.usecurling.com/p/400/300?q=vegetable%20omelette',
    calories: 280,
    protein: 18,
    carbs: 8,
    fats: 20,
    prepTime: 10,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Salgadas',
    tags: ['Vegetariano', 'Low Carb'],
    ingredients: [
      { name: 'Ovos Grandes', amount: '3 unid', category: 'Carnes/Proteínas' },
      { name: 'Espinafre', amount: '50g', category: 'Hortifrúti' },
      { name: 'Queijo Branco', amount: '30g', category: 'Laticínios' },
      { name: 'Tomate', amount: '1/2 unid', category: 'Hortifrúti' },
    ],
    instructions: [
      'Em um bowl, bata os ovos com uma pitada de sal e orégano.',
      'Pique o espinafre e o tomate em pedaços pequenos.',
      'Misture os vegetais e o queijo em cubos aos ovos batidos.',
      'Despeje em uma frigideira antiaderente untada e aquecida.',
      'Cozinhe em fogo baixo com a tampa por 3 minutos.',
      'Dobre a omelete ao meio e deixe dourar por mais 1 minuto.',
    ],
    rating: 4.6,
  },
  {
    id: '6',
    title: 'Iogurte com Frutas Vermelhas',
    image: 'https://img.usecurling.com/p/400/300?q=yogurt%20berries',
    calories: 220,
    protein: 12,
    carbs: 30,
    fats: 6,
    prepTime: 5,
    portions: 1,
    difficulty: 'Fácil',
    category: 'Doces',
    tags: ['Vegetariano'],
    ingredients: [
      { name: 'Iogurte Natural', amount: '170g', category: 'Laticínios' },
      { name: 'Morangos', amount: '5 unid', category: 'Hortifrúti' },
      { name: 'Mirtilos', amount: '1 punhado', category: 'Hortifrúti' },
      { name: 'Mel', amount: '1 col. chá', category: 'Despensa' },
      { name: 'Chia', amount: '1 col. chá', category: 'Despensa' },
    ],
    instructions: [
      'Lave e seque bem as frutas vermelhas.',
      'Pique os morangos em pedaços menores.',
      'Em uma taça, coloque metade do iogurte.',
      'Adicione uma camada de frutas e mel.',
      'Cubra com o restante do iogurte e finalize com mais frutas e sementes de chia.',
    ],
    rating: 4.7,
  },
]
